spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent_output: true
  metrics:
    servo:
      enabled: false
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
security:
  token:
    endpoint: http://uaa-service/api/user
    header: X-Token
management:
  context-path: /
  security.enabled: false